### PR TITLE
style(ndm): Fix go vet errors in fdutil_test.go

### PR DESCRIPTION
**Pull request by bege13mot**
https://github.com/openebs/node-disk-manager/issues/111

Signed-off-by: bege13mot <bege13mot@gmail.com>

### CODE REVIEW

**Comment by shovanmaity** [comment]
@bege13mot thanks for this pr, changes looks good. You can change function `getFdArray` so that it can take value and return one fdset for that value it will be more generic.
something like -
```
func getFdSet(value int64) syscall.FdSet {
	// return fdset for value
}
```

**Comment by shovanmaity** [comment]
Yes It will be good if you make those changes. thanks again :+1: . Just thinking why it requires `int32`
It should take `int64` - https://golang.org/src/syscall/ztypes_linux_amd64.go#L546 can you put some error log or message

**Comment by bege13mot** [comment]
Hi @shovanmaity ,

As I understand, `syscall.FdSet` depends on the system platform. And on my machine it `int32`. Like https://golang.org/src/syscall/ztypes_darwin_amd64.go

**Comment by shovanmaity** [comment]
> Hi @shovanmaity ,
> 
> As I understand, `syscall.FdSet` depends on the system platform. And on my machine it `int32`. Like https://golang.org/src/syscall/ztypes_darwin_amd64.go

@bege13mot changes are good as it is dependent on system no need to update. +1

**Pull request merged**
