### PR TITLE
Fix Potential Integer overflow made by strconv.Atoi result conversion to int16/32

### PR DESCRIPTION
**Pull request by soniasingla**
## Pull Request template

**Why is this PR required? What issue does it fix?**:

**What this PR does?**:

**Does this PR require any upgrade changes?**:

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Any additional information for your reviewer?** : 
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Fixes #<issue number>
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Has the change log section been updated? 
- [ ] Commit has unit tests
- [ ] Commit has integration tests
- [ ] (Optional) Are upgrade changes included in this PR? If not, mention the issue/PR to track: 
- [ ] (Optional) If documentation changes are required, which issue on https://github.com/openebs/openebs-docs is used to track them: 

**PLEASE REMOVE BELOW INFORMATION BEFORE SUBMITTING**

The PR title message must follow convention:
   `<type>(<scope>): <subject>`.

Where:
    Most common types are:
    * `feat`        - for new features, not a new feature for build script
    * `fix`         - for bug fixes or improvements, not a fix for build script
    * `chore`       - changes not related to production code
    * `docs`        - changes related to documentation
    * `style`       - formatting, missing semi colons, linting fix etc; no significant production code changes
    * `test`        - adding missing tests, refactoring tests; no production code change
    * `refactor`    - refactoring production code, eg. renaming a variable or function name, there should not be any significant production code changes
    * `cherry-pick` - if PR is merged in master branch and raised to release branch(like v0.4.x)
    
IMPORTANT: Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.

### CODE REVIEW

**Review by akhilerm — CHANGES_REQUESTED** [review]
@soniasingla Can you make sure the tests pass and the code compiles ?

**Comment by akhilerm** [comment]
@soniasingla Can you update on this PR?

**Comment by akhilerm** [comment]
@soniasingla Are there any updates on this PR?

**Comment by soniasingla** [comment]
@akhilerm can you help me with what i need to pass, i did not get it? thanks

**Comment by akhilerm** [comment]
@soniasingla the `pages` expect an `int32` value. But if you are using `Atoi()` for conversion, it results in overflow. So you can use `ParseInt()` method, so that the correct bit size integer is returned. 

example:
```golang
pages, err := strconv.ParseInt(strings.TrimRight(string(hugepages), "\n"), 10, 32)
```

**Comment by soniasingla** [comment]
> @soniasingla the `pages` expect an `int32` value. But if you are using `Atoi()` for conversion, it results in overflow. So you can use `ParseInt()` method, so that the correct bit size integer is returned.
> 
> example:
> 
> ```go
> pages, err := strconv.ParseInt(strings.TrimRight(string(hugepages), "\n"), 10, 32)
> ```

Done thanks @akhilerm

**Review by akhilerm — APPROVED** [review]
LGTM.

Will merge once the CI passes.

**Comment by soniasingla** [comment]
@akhilerm did not get why its failing can you help me thanks

**Comment by akhilerm** [comment]
@soniasingla . It was a flaky test. I have restarted and it passed now.

**Review by akhilerm — APPROVED** [review]
LGTM

**Pull request merged**
