### PR TITLE
chore(REAMDE): update project status

### PR DESCRIPTION
**Pull request by akhilerm**
Signed-off-by: Akhil Mohan <akhil.mohan@mayadata.io>

### CODE REVIEW

**Review by shubham14bajpai — APPROVED** [review]
LGTM

**Comment by shubham14bajpai** [comment]
Can we add the condtition `if: ${{ (github.event.ref_type == 'branch') }}` on lint and unit-tests?

**Comment by akhilerm** [comment]
@shubham14bajpai Have made the changes for lint and unit-tests.  integration tests will still be run . WDYT?

**Comment by shubham14bajpai** [comment]
> @shubham14bajpai Have made the changes for lint and unit-tests. integration tests will still be run . WDYT?
Not required imo. Also should the integration test depend on unit-tests?

**Comment by akhilerm** [comment]
> Not required imo. Also should the integration test depend on unit-tests?

No, it is run separately . It has no dependencies and no job is dependent on integration tests too.

**Review by shubham14bajpai — APPROVED** [review]
LGTM

**Review by kmova — APPROVED** [review]

**Pull request merged**
