### PR TITLE
chore(dep): bumps go version to 1.19

### PR DESCRIPTION
**Pull request by akhilerm**
Signed-off-by: Akhil Mohan <akhilerm@gmail.com>

## Pull Request template

**Why is this PR required? What issue does it fix?**:
build was using a deprecated version of golang

**What this PR does?**:
- update go.mod / go.sum
- update vendor directory
- update build base image with go 1.19.3

**Does this PR require any upgrade changes?**: No

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Any additional information for your reviewer?** : 
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Fixes #<issue number>
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [x] Has the change log section been updated? 
- [ ] Commit has unit tests
- [ ] Commit has integration tests
- [ ] (Optional) Are upgrade changes included in this PR? If not, mention the issue/PR to track: 
- [ ] (Optional) If documentation changes are required, which issue on https://github.com/openebs/openebs-docs is used to track them:

### CODE REVIEW

**Comment by niladrih** [comment]
CI changes in PR https://github.com/openebs/node-disk-manager/pull/682.

**Review by niladrih — COMMENTED** [review]
You might want to remove the vendor directory.

**Comment by akhilerm** [comment]
> You might want to remove the vendor directory.

@niladrih Arent we not keeping the vendor directory upto date now? I think with latest go version that should also work

**Comment by niladrih** [comment]
@akhilerm -- The vendor directory was required prior to go modules. We should be able to build without it...

**Comment by akhilerm** [comment]
The changes are included in #682

**Pull request closed without merging**
