### PR TITLE
fix(yaml): Fix '==' typo in exporter args

### PR DESCRIPTION
**Pull request by fengye87**
## Pull Request template

**Why is this PR required? What issue does it fix?**:

Exporter failed to start due to '==' typos in YAML file

**What this PR does?**:

Fix the typo

**Does this PR require any upgrade changes?**:

No

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Any additional information for your reviewer?** : 
_Mention if this PR is part of any design or a continuation of previous PRs_

### CODE REVIEW

**Review by akhilerm — APPROVED** [review]
LGTM

**Review by Ab-hishek — APPROVED** [review]
LGTM

**Review by Ab-hishek — CHANGES_REQUESTED** [review]
Can you do the same changes in the helm templates for exporters?

**Comment by Ab-hishek** [comment]
Sorry, my bad! The templates are already correct.

**Review by Ab-hishek — APPROVED** [review]

**Comment by akhilerm** [comment]
Thanks @fengye87 for fixing this.

**Pull request merged**
