### PR TITLE
fix(filter): add `block-device-tag` filter during manual claiming

### PR DESCRIPTION
**Pull request by akhilerm**
Signed-off-by: Akhil Mohan <akhil.mohan@mayadata.io>

### CODE REVIEW

**Comment by akhilerm** [comment]
`block-device-tag` will not be checked if the BlockDevice is claimed manually.

**Comment by kmova** [comment]
Re-opening as it came up with https://github.com/openebs/node-disk-manager/pull/430

**Review by kmova — APPROVED** [review]

**Comment by kmova** [comment]
@akhilerm -- can you update with change log please.

**Comment by akhilerm** [comment]
Done @kmova

**Review by kmova — APPROVED** [review]

**Comment by kmova** [comment]
The changes in this PR look good. This change will help with avoiding cases where  BD reserved to be used by Local PV is not claimed by SPC. However, merging this might break some high-level automation scripts around cStor pool creation. 

cStor Pool creation (SPC and CSPC) is adding a new feature to take as input "allowed-block-device-tags", so the BDs should be configed to the white-listed BD tags for a given SPC or CSPC. 

This PR will be merge once the above changes are implemented. ( cc: @sonasingh46 )

**Comment by akhilerm** [comment]
The changes required are merged in the PR [172](https://github.com/openebs/cstor-operators/pull/172),  [69](https://github.com/openebs/api/pull/69) and [1748](https://github.com/openebs/maya/pull/1748)

**Pull request merged**
