### PR TITLE
style(ndm): Fixed lint errors - cmd/controller/filter.go

### LINKED ISSUE #106: Fix lint errors in filter.go
File: [filter.go](https://github.com/openebs/node-disk-manager/blob/master/cmd/controller/filter.go)

```
Line 31: warning: comment on exported method Filter.ApplyFilter should be of the form "ApplyFilter ..." (golint)
Line 52: warning: comment on exported type Filters should be of the form "Filters ..." (with optional leading article) (golint)
```

### PR DESCRIPTION
**Pull request by gunjan01**
This PR fixes lint errors in filter.go (Line 31 and 52). It fixes #106 

Signed-off-by: gunjan01 <gunjan.tank9@gmail.com>

### CODE REVIEW

**Comment by gunjan01** [comment]
@a4abhishek  How do I fix the failing check ?

**Comment by shovanmaity** [comment]
> @a4abhishek How do I fix the failing check ?

@gunjan01 try to update your branch with openebs/node-disk-manager(master) and push it again it is showing some changes which you have not made in your pr. This may solve this problem.
screenshot from 2018-10-03 09-37-06

**Comment by gunjan01** [comment]
@shovanmaity  Updated. Still no luck

**Comment by shovanmaity** [comment]
> @shovanmaity Updated. Still no luck

:slightly_smiling_face: merging it !!!

**Comment by gunjan01** [comment]
@shovanmaity  Thanks a bunch ! :)

**Pull request merged**
